### ISSUE TITLE
Moduł informowania o stanie sprawności automatu

### ISSUE THREAD

**Issue by darekb74** [darekb74/WSIZ_SW_Projekt1#1]
Moduł powinien monitorować czujniki automatu (ilość kubków, podłączenie wody, ilość mleka, ilość kawy, bilon zwrotny) i w przypadku niesprawności któregoś z elementów informować o tym moduł główny.

**Comment by slowikDevOps** [comment]
Dodałem moduł. Jak by coś trzeba było poprawić dajcie znać :> Dzięki za rady.
